version: "3"

services:

  app:
    image: eu.gcr.io/digdir-fdk-infra/records-of-processing-activities:test
    build: .
    ports:
      - "8081:8080"
    environment:
      - SSO_HOST=https://sso.staging.fellesdatakatalog.digdir.no
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
