logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.springframework.security: TRACE
  level.org.apache.jena.riot: ERROR
server:
  port: 8085
spring:
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${OIDC_JWKS}
    issuer-uri: ${OIDC_ISSUER}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/recordsDB?authSource=admin&authMechanism=SCRAM-SHA-1

---
spring:
  config.activate.on-profile: develop
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/recordsDB?authSource=admin&authMechanism=SCRAM-SHA-1

---
spring:
  config.activate.on-profile: integration-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5000/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5000/auth/realms/fdk
