name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-deploy-production:
    name: Build, test, publish and deploy to production environment on merge to main branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java jdk
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Setup gcloud CLI for image-store
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker eu.gcr.io

      - name: Package & run tests with maven
        run: mvn clean install --no-transfer-progress

      - name: Build Docker image with latest tag
        run: docker build . -t eu.gcr.io/digdir-fdk-infra/records-of-processing-activities:$GITHUB_SHA -t eu.gcr.io/digdir-fdk-infra/records-of-processing-activities:latest

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/digdir-fdk-infra/records-of-processing-activities -a

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/records-of-processing-activities
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/records-of-processing-activities:$GITHUB_SHA" \
           -f ./helm/records-of-processing-activities/values/prod.yaml ./helm/records-of-processing-activities/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Setup gcloud CLI for deploy
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
          export_default_credentials: true

      - name: Deploy to GCP
        run: |
          gcloud container clusters get-credentials digdir-fdk-prod --region europe-north1-a --project digdir-fdk-prod
          kubectl apply -f ./kubectlapply.yaml --force

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: records-of-processing-activities | Environment: prod'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo
          client-payload: '{"sha": "${{ github.sha }}"}'
